model:
  lr: 1.0e-05
  max_iter: 81000
  test_iter: 87
retrain: false
solver:
  adam: /media/compute/homes/galberding/FleckDetect/scripts/model/adam_solver.prototxt
weights:
  base: /media/compute/homes/galberding/FleckDetect/scripts/model/weights.caffemodel
  retrain: /media/compute/homes/galberding/FleckDetect/workspaces/combined/ras_soc_msrab_combi_iter_80000.caffemodel
